stages:
  - test

default:
  tags:
    - docker


unit-test:
  stage: test
  #image: python 3.10
  script:
    echo "started runner"

    #- pip install pytest pytest-cov
    #- python -m pytest --cov-report=html --cov=src .
  #artifacts:
    #paths:
      #- coverage
    #expire_in: 30 days