image: node:18.15.0-alpine3.17

stages:
  - build
  - test

build:
  stage: build
  script:
      - cd nanoindentation-dashboard
      - npm ci
  cache:
    paths:
      -  nanoindentation-dashboard/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      -  nanoindentation-dashboard/node_modules/

test:
  image: node:16
  stage: test
  dependencies:
    - build
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - cd nanoindentation-dashboard
    - npm run test:ci
