image: 

stages:
  - build
  - test  


build:
  image: node:18.15.0-alpine
  stage: build
  script:
    - cd nanoindentation-dashboard
    - npm ci
    - export CHROME_BIN=/usr/bin/chromium-browser
  cache:
    paths:
      -  nanoindentation-dashboard/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      -  nanoindentation-dashboard/node_modules/


test:
  image: marinasjp/ese2:latest
  stage: test
  dependencies:
    - build
  script:
    - cd nanoindentation-dashboard
    - npm run test:ci
