image: node:18.15.0-alpine

stages:
  - build
  - test

before_script:
  - cd nanoindentation-dashboard
  - npm ci
  - export CHROME_BIN=/usr/bin/chromium-browser


build:
  image: marinasjp/ese2:latest
  stage: build
  script:
    - npm ci
  cache:
    paths:
      -  nanoindentation-dashboard/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      -  nanoindentation-dashboard/node_modules/


test:
  image: marinasjp/ese2:latest
  stage: test
  dependencies:
    - build
  script:
    - cd nanoindentation-dashboard
    - npm run test:ci
