image: python:3.8

stages:
  - test

before_script:
  - pip install numpy
  - pip install scipy

unit-test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - python -m pytest --import-mode=append ./nanoindentation-dashboard/src/Processor/Processes/
