image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
      - cd nanoindentation-dashboard
    #   - yarn
      - npm ci
  cache:
    paths:
      -  nanoindentation-dashboard/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      -  nanoindentation-dashboard/node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
      - cd nanoindentation-dashboard
      - npm run test:ci
    #   - yarn test:ci
