
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: python 3.8
  script:
    - echo "Running unit tests..."
    - pip install pytest pytest-cov
    - python -m pytest --cov-report=html --cov=src .
    artifacts: 
        paths: 
            coverage
        expire_in: 30 days