image: node:16

stages:
  - build
  - test

build:
  stage: build
  script:
      - cd nanoindentation-dashboard
    #   - yarn
      - npm ci
  cache:
    paths:
      -  nanoindentation-dashboard/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      -  nanoindentation-dashboard/node_modules/

test:
    image: node:16
    stage: test
    dependencies:
        - build
    script:
      - cd nanoindentation-dashboard
      - npm run testspec
