
stages:
  # - build
  - test

unit-test:
  image: python:3.8
  stage: test
  before_script:
  - pip install numpy
  - pip install scipy
  - pip install pytest
  script:
    - python -m pytest --import-mode=append ./nanoindentation-dashboard/src/Processor/Processes/
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - cache/

# build:
#   image: node:16
#   stage: build
#   script:
#       - cd nanoindentation-dashboard
#       - npm ci
#   cache:
#     paths:
#       -  nanoindentation-dashboard/node_modules/
#   artifacts:
#     expire_in: 1 days
#     when: on_success
#     paths:
#       -  nanoindentation-dashboard/node_modules/

# test:
#     image: node:16
#     stage: test
#     dependencies:
#         - build
#     script:
#       - cd nanoindentation-dashboard
#       - npm i string.prototype.replaceall
#       - npm run test
