image: node:18.15.0-alpine3.17

stages:
  - build
  - test

build:
  stage: build
  script:
      - cd nanoindentation-dashboard
      - npm ci
  cache:
    paths:
      -  nanoindentation-dashboard/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      -  nanoindentation-dashboard/node_modules/

test:
  stage: test
  dependencies:
    - build
  before_script:
    - apk update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apk add dpkg
    - dpkg --add-architecture amd64
    - dpkg -i ./google-chrome-stable_current_amd64.deb
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - cd nanoindentation-dashboard
    - npm run test:ci
