image: python:3.8

stages:
  - test

before_script:
  - pip install numpy
  - pip install scipy
  - pip install pytest

unit-test:
  stage: test
  script:
    - python -m pytest --import-mode=append ./nanoindentation-dashboard/src/Processor/Processes/
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - cache/