image: node:14.20

stages:
  - build
  - test

build:
  stage: build
  script:
    - yarn
  cache:
    paths:
      -  nanoindentation-dashboard/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      -  nanoindentation-dashboard/node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
      - cd  nanoindentation-dashboard
      - yarn test:ci
