image: python:3.8

stages:
  - install
  - test

installs:
  stage: install
  script:
    - pip install numpy
    - pip install scipy

unit-test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - python -m pytest --cov-report=html --cov=src .
  artifacts:
    paths:
      - coverage
    expire_in: 30 days
